left_wheel_effort_controller:
  type: effort_controllers/JointEffortController
  joint: base_left_wheel_joint

right_wheel_effort_controller:
  type: effort_controllers/JointEffortController
  joint: base_right_wheel_joint

caster_effort_controller:
  type: effort_controllers/JointEffortController
  joint: caster_joint
  
front_wheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_abc_joint
  pid: {p: 10.0, i: 0.0, d: 0.5}
  
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

